[package]
name = "SCHCLIENT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
encoding_rs = "0.8.30"
lazy_static = "1.4.0"
regex = "1.5.5"
reqwest = {version="0.11.10", features=["gzip"]}
scraper = "0.12.0"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
tokio = { version="1.17.0", features=["full"] }
url = "2.2.2"
