[package]
name = "termch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.52"
configparser = "3.0.0"
confy = { version = "0.4.0", default-features = true }
dirs = "4.0.0"
encoding_rs = "0.8.30"
lazy_static = "1.4.0"
percent-encoding = "2.1.0"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["gzip", "cookies"] }
scraper = "0.12.0"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
serde_urlencoded = "0.7.1"
tokio = { version = "1.17.0", features = ["full"] }
url = "2.2.2"

[features]
