[package]
name = "termchan"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "core"
path = "core"

[[bin]]
name = "cli"
path = "cli"

[workspace]
members = ["cli", "core"]
default-members = ["core"]
