bbsmenu:
    url:
        - https://menu.2ch.sc/bbsmenu.html
liked_board_path:
    custom: false
    path: $HOME/.config/termchan/liked.json

login:
    url: http
    email: email@example.com
    password: password

post:
    use_login: false
    repost_interval: 0

proxy:
    url: https://your.proxy.domain:1234
    username: user
    password: password
