//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "board_bookmark")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id:       i32,
    pub rating:   i32,
    pub board_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::board::Entity",
        from = "Column::BoardId",
        to = "super::board::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Board,
}

impl Related<super::board::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Board.def()
    }
}

impl ActiveModelBehavior for ActiveModel {
}
