//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub mod prelude;

pub mod board;
pub mod board_bookmark;
pub mod category;
pub mod menu;
pub mod thread;
pub mod thread_post;
pub mod thread_post_image;
