//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub use super::{
    board::Entity as Board,
    board_bookmark::Entity as BoardBookmark,
    category::Entity as Category,
    image::Entity as Image,
    menu::Entity as Menu,
    thread::Entity as Thread,
    thread_post::Entity as ThreadPost,
};
